#!/usr/bin/env bash
# Install and configure nginx
# to return 'Hello World!' on a GET request to /

function install_and_configure_nginx() {
    # Update package lists
    sudo apt-get update

    # Install Nginx
    sudo apt-get -y install nginx

    # Configure Nginx to return 'Hello World!' on a GET request to /
    echo 'server {
        listen 80 default_server;
        server_name _;
        root /var/www/html;

        location / {
            return 200 "Hello World!";
        }
    }' | sudo tee /etc/nginx/sites-available/default > /dev/null

    # Restart Nginx using the service command
    sudo service nginx restart
}

install_and_configure_nginx
