#!/usr/bin/env bash
# Install Nginx, configure it to listen on port 80, and print "Hello World"

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx using the service command
sudo service nginx restart

# Create an HTML page with "Hello World!"
echo '<!DOCTYPE html>
<html>
<head>
    <title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
