#!/usr/bin/env bash
# Bash script to install and configure HAProxy on lb-01 server

# Update the package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
haproxy_config="/etc/haproxy/haproxy.cfg"
sudo mv $haproxy_config{,.backup}  # Backup the original configuration

# Define the new HAProxy configuration
new_config="global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 273403-web-01 35.153.98.78:80 check
    server 273403-web-02 52.91.160.173:80 check"

# Apply the new HAProxy configuration
echo -e "$new_config" | sudo tee $haproxy_config

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy

# Ensure HAProxy starts on boot
sudo systemctl enable haproxy
