#!/usr/bin/env bash
# Script accepts string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times

# Check if an IP address argument is provided
if [ $# -ne 1 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Get the IP address from the command line argument
ip_address="$1"

# Ping the IP address 5 times
ping -c 5 "$ip_address"
