#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
rm default;                                                                                                                                               
ln -s /etc/nginx/sites-available/default default;                                                                                                         
sudo service nginx restart
