#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Ensure Nginx is running
sudo service nginx start

# Configure Nginx to listen on port 80
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf

# Reload Nginx for the changes to take effect
sudo service nginx reload
