#!/usr/bin/env bash
# This script configures Nginx to listen on port 80
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 8080 default_server;/listen 80;/g' /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart || sudo service nginx start
sudo pkill -o nginx
