#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/myscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/myscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

# Function to handle SIGTERM and SIGQUIT signals
terminate() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to handle SIGINT signal
interrupt() {
    echo "Y U no love me?!"
}

# Trap signals
trap 'terminate' SIGTERM SIGQUIT
trap 'interrupt' SIGINT

# Create a PID file
echo "$$" > /var/run/myscript.pid

# Display messages indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
