#!/usr/bin/env bash

# This script performs various actions on signals.
# It does  the following
# - Creates a file
# - Display "To infinity and beyond"
# - Displays a message when receiving SIGTERM signal
# - Displays a message when receiving SIGINT signal
# - Deletes the created file

terminate() {
    rm -f /var/run/myscript.pid
    exit 
}

# Create a PID file
echo "$$" > /var/run/myscript.pid

# Display messages indefinitely and handle signals
while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me??"' SIGINT
    trap 'echo "I hate the kill command" && terminator' SIGTERM
    trap 'terminator' SIGQUIT
done
