#!/usr/bin/env bash
# script displays a message indefinitely and responds to SIGTERM.

# Define a function to handle the SIGTERM signal
terminate() {
    echo "I am invincible!!!"
    exit 0
}

# Trap the SIGTERM signal and associate it with the terminate function
trap 'terminate' SIGTERM

# Start an infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

