#!/usr/bin/env bash
# script displays formatted user information from /etc/passwd.

# Define the file path
passwd_file="/etc/passwd"

# Use a while loop to read and process each line of the file
while IFS=: read -r username password uid gid info home shell
do
    # Extract the user's group name based on the group ID
    group_name=$(getent group "$gid" | cut -d: -f1)

    # Display formatted user information
    echo "The user $username is part of the $group_name gang,"\
    "lives in $home and rides $shell. USER ID's place is protected by the passcode $password,"\
    "more info about the user here: $uid $info"
done < "$passwd_file"
