#!/usr/bin/env bash
# script displays "Best School" nine times and Hi one time

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
