#!/usr/bin/env bash
# This script configures a ufw firewall to block all incoming traffic
# except for TCP ports 22, 443, and 80.

# Install ufw
sudo apt-get install ufw

# Enable IPv6 support in ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Disable ufw (if already enabled)
sudo ufw disable

# Enable ufw
sudo ufw enable

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
