#!/usr/bin/env bash
# Script to run process as nginx user
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user\s*[^;]*/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen\s*80;/c\ listen 8080;' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
